function contracts = create_interface_buses()
%CREATE_INTERFACE_BUSES Define the V5.4.1 executable interface contracts.
% All angles are radians, rates are rad/s, distances are metres, time is
% seconds and protocol-level PWM values are PWM-equivalent microseconds.

contracts = struct;
contracts.RCCommandBus = makeBus({ ...
    "normalized",4,"double","[-1,1] normalized RC demand"; ...
    "channel_pwm_us",8,"double","PWM-equivalent microseconds"; ...
    "timestamp_s",1,"double","simulation time"; ...
    "valid",1,"double","0/1 validity"});
contracts.ActuatorCommandBus = makeBus({ ...
    "ordered_pwm_us",5,"double", ...
        "[throttle,left aileron,right aileron,elevator,rudder] PWM us"; ...
    "timestamp_s",1,"double","last JSON exchange time"; ...
    "frame_count",1,"double","SITL servo frame counter"; ...
    "frame_rate_hz",1,"double","SITL servo packet rate"; ...
    "valid",1,"double","0/1 validity"});
contracts.SurfaceStateBus = makeBus({ ...
    "physical_state",5,"double", ...
        "[throttle,left,right,elevator,rudder], fraction/rad"; ...
    "physical_rate",5,"double","fraction/s or rad/s"; ...
    "saturated",5,"double","0/1 mechanical saturation"; ...
    "timestamp_s",1,"double","simulation time"; ...
    "valid",1,"double","0/1 validity"});
contracts.TruthStateBus = makeBus({ ...
    "position_ned_m",3,"double","NED position"; ...
    "velocity_body_mps",3,"double","body translational velocity"; ...
    "rates_body_radps",3,"double","body angular rates"; ...
    "euler_rad",3,"double","roll,pitch,yaw"; ...
    "alpha_beta_rad",2,"double","angle of attack,sideslip"; ...
    "airspeed_mps",1,"double","true airspeed used by plant"; ...
    "altitude_m",1,"double","positive-up relative altitude"; ...
    "timestamp_s",1,"double","simulation time"; ...
    "valid",1,"double","0/1 validity"});
contracts.SensorBus = makeBus({ ...
    "position_ned_m",3,"double","sensor-model NED position"; ...
    "velocity_body_mps",3,"double","sensor-model body velocity"; ...
    "rates_body_radps",3,"double","sensor-model body rates"; ...
    "euler_rad",3,"double","sensor-model Euler attitude"; ...
    "alpha_beta_rad",2,"double","sensor-model aerodynamic angles"; ...
    "airspeed_mps",1,"double","sensor-model airspeed"; ...
    "altitude_m",1,"double","sensor-model relative altitude"; ...
    "timestamp_s",1,"double","simulation time"; ...
    "valid",1,"double","0/1 validity"});

names = fieldnames(contracts);
for k = 1:numel(names)
    assignin("base",names{k},contracts.(names{k}));
end
end

function bus = makeBus(spec)
elements = repmat(Simulink.BusElement,size(spec,1),1);
for k = 1:size(spec,1)
    element = Simulink.BusElement;
    element.Name = char(spec{k,1});
    element.Dimensions = spec{k,2};
    element.DataType = char(spec{k,3});
    element.Description = char(spec{k,4});
    elements(k) = element;
end
bus = Simulink.Bus;
bus.Elements = elements;
end
