function servo = load_servo_configuration(servoDataRoot)
%LOAD_SERVO_CONFIGURATION Load the V5.4.1 PWM/deflection calibration.
% The Excel table is authoritative for static calibration. Dynamic data are
% taken from the colocated HS-225BB sources and every value carries a source
% classification required by the V5.4.1 data hierarchy.

arguments
    servoDataRoot (1,1) string
end

excelFile = fullfile(servoDataRoot,"pwm波到副翼偏角.xlsx");
if ~isfile(excelFile)
    error("UAVV541:ServoExcelMissing", ...
        "Measured servo calibration workbook is missing: %s",excelFile);
end

raw = readmatrix(excelFile);
raw = raw(:,1:2);
raw = raw(all(isfinite(raw),2),:);
if height(raw) < 3 || any(diff(raw(:,1)) <= 0)
    error("UAVV541:ServoExcelInvalid", ...
        "Servo calibration must contain at least three increasing PWM points.");
end

pwm = raw(:,1)';
deflection = raw(:,2)';
if ~isMonotonic(deflection)
    error("UAVV541:ServoDeflectionNonMonotonic", ...
        "Measured deflection must be monotonic for auditable inversion.");
end

neutralPwm = interp1(deflection,pwm,0,"linear");
if ~isfinite(neutralPwm)
    [~,neutralIndex] = min(abs(deflection));
    neutralPwm = pwm(neutralIndex);
end

common = struct( ...
    "PWM_breakpoints",pwm, ...
    "deflection_deg",deflection, ...
    "basic_deflection_normalized",normalizeCurve(deflection), ...
    "neutral_pwm",neutralPwm, ...
    "min_pwm",min(pwm), ...
    "max_pwm",max(pwm), ...
    "rate_positive_deg_s",370, ...
    "rate_negative_deg_s",370, ...
    "delay_s",0.004, ...
    "time_constant_s",0.035, ...
    "deadband_pwm",5, ...
    "interpolation","linear", ...
    "extrapolation","boundary_saturation", ...
    "raw_excel_file",excelFile, ...
    "dynamic_reference",fullfile(servoDataRoot, ...
        "Lakshminarayan_16MS_ModelBasedFaultDetection.pdf"), ...
    "specification_reference",fullfile(servoDataRoot, ...
        "HCS_HS-225BB_Specsheetv2.2_1-1729888831.pdf"));

% The measured Excel curve is a signed BASIC servo/left-aileron curve.
% direction maps worksheet motion into the plant's aerodynamic sign.  It
% is intentionally independent of the physical endpoint magnitudes.
% Mechanical limits remain independent so installation direction and
% aileron differential can never be conflated.
servo.aileron_left = surface(common,-1,[-30.55,37.85], ...
    "MEASURED", ...
    "Measured left curve; installed aerodynamic sign is opposite worksheet sign");
servo.aileron_right = surface(common,+1,[-37.85,30.55], ...
    "ASSUMED_FROM_LEFT_AILERON", ...
    "Mirrored installation; curve and endpoint magnitudes assumed from left aileron");
servo.elevator = surface(common,+1,[-12,10], ...
    "ASSUMED_FROM_LEFT_AILERON", ...
    "Left-aileron base curve reused and scaled to configured elevator travel");
servo.rudder = surface(common,-1,[-22,22], ...
    "ASSUMED_FROM_LEFT_AILERON", ...
    "Left-aileron base curve reused and scaled to configured rudder travel");

servo.throttle = struct( ...
    "PWM_breakpoints",[980,1900],"deflection_deg",[0,1], ...
    "neutral_pwm",980,"min_pwm",980,"max_pwm",1900, ...
    "min_deflection_deg",0,"max_deflection_deg",1, ...
    "rate_positive_deg_s",inf,"rate_negative_deg_s",inf, ...
    "delay_s",0,"time_constant_s",0,"deadband_pwm",0, ...
    "direction",1,"installation_sign",1, ...
    "data_source","ASSUMED_NON_SURFACE", ...
    "source_reason","Calibrated throttle normalization retained");

servo.channel_order = ["throttle","aileron_left","aileron_right", ...
    "elevator","rudder"];
servo.data_conflict = struct( ...
    "parameter","neutral_pwm", ...
    "excel_value_us",neutralPwm, ...
    "txt_and_spec_value_us",1500, ...
    "resolution","Excel static calibration used; no averaging", ...
    "authoritative_source","MEASURED");
end

function value = surface(common,installationSign,limits,source,reason)
value = common;
value.direction = installationSign;
value.installation_sign = installationSign;
value.min_deflection_deg = limits(1);
value.max_deflection_deg = limits(2);
value.data_source = source;
value.source_reason = reason;
value.source_tags = struct( ...
    "PWM_breakpoints","MEASURED", ...
    "deflection_deg","MEASURED", ...
    "neutral_pwm","MEASURED", ...
    "rate_positive_deg_s","OPEN_SOURCE", ...
    "rate_negative_deg_s","OPEN_SOURCE", ...
    "delay_s","OPEN_SOURCE", ...
    "time_constant_s","ASSUMED", ...
    "deadband_pwm","OPEN_SOURCE", ...
    "mechanical_limits",source);
end

function normalized = normalizeCurve(deflection)
normalized = zeros(size(deflection));
positiveScale = max(deflection);
negativeScale = abs(min(deflection));
positive = deflection >= 0;
normalized(positive) = deflection(positive)/max(positiveScale,eps);
normalized(~positive) = deflection(~positive)/max(negativeScale,eps);
end

function tf = isMonotonic(values)
difference = diff(values);
tf = all(difference >= 0) || all(difference <= 0);
end
