function parameterTable = mission_planner_parameter_table(P)
%MISSION_PLANNER_PARAMETER_TABLE Build and validate portable ArduPlane output.
% A bundled schema makes the folder self-contained. When Mission Planner or
% a target-aircraft Full Parameter List is available, both are additionally
% checked before export.

[names, groups, optimized, minimum, maximum, units, meaning] = bundledSchema();
values = zeros(size(names));
for k = 1:numel(names)
    field = char(names(k));
    if ~isfield(P.ap, field)
        error("UAV:MissingArduPlaneField", ...
            "uav_config.m is missing P.ap.%s.", field);
    end
    values(k) = P.ap.(field);
end

validation = repmat("bundled ArduPlane schema", size(names));
metadataFile = string(P.mp.metadata_file);
if strlength(metadataFile) > 0 && isfile(metadataFile)
    metadataText = fileread(metadataFile);
    planeToken = regexp(metadataText, ...
        '<ArduPlane>([\s\S]*?)</ArduPlane>', 'tokens', 'once');
    if isempty(planeToken)
        error("UAV:ArduPlaneMetadataMissing", ...
            "The metadata file has no <ArduPlane> section: %s", metadataFile);
    end
    planeText = planeToken{1};
    for k = 1:numel(names)
        escapedName = regexptranslate('escape', char(names(k)));
        pattern = ['<' escapedName '>([\s\S]*?)</' escapedName '>'];
        parameterToken = regexp(planeText, pattern, 'tokens', 'once');
        if isempty(parameterToken)
            validation(k) = "target Full Parameter List authority; absent from installed generic metadata";
            continue
        end
        rangeToken = regexp(parameterToken{1}, ...
            '<Range>\s*([-+0-9.eE]+)\s+([-+0-9.eE]+)\s*</Range>', ...
            'tokens', 'once');
        if ~isempty(rangeToken)
            installedMinimum = str2double(rangeToken{1});
            installedMaximum = str2double(rangeToken{2});
            if minimum(k) < installedMinimum || maximum(k) > installedMaximum
                error("UAV:BundledRangeMismatch", ...
                    "Bundled range for %s is wider than installed Mission Planner metadata.", ...
                    names(k));
            end
        end
    end
    metadataMatched = validation == "bundled ArduPlane schema";
    validation(metadataMatched) = "bundled schema + installed ArduPlane metadata";
end

for k = 1:numel(names)
    if ~isfinite(values(k)) || values(k) < minimum(k) || values(k) > maximum(k)
        error("UAV:MissionPlannerValueOutOfRange", ...
            "%s=%.9g is outside the supported range [%.9g, %.9g].", ...
            names(k), values(k), minimum(k), maximum(k));
    end
end

vehicleFile = string(P.mp.vehicle_parameter_file);
if strlength(vehicleFile) > 0
    if ~isfile(vehicleFile)
        error("UAV:VehicleParameterFileMissing", ...
            "Configured vehicle parameter file was not found: %s", vehicleFile);
    end
    vehicleText = fileread(vehicleFile);
    for k = 1:numel(names)
        pattern = ['(?m)^\s*' regexptranslate('escape', char(names(k))) ...
            '\s*(?:,|\s)'];
        if isempty(regexp(vehicleText, pattern, 'once'))
            error("UAV:ParameterAbsentOnTarget", ...
                "%s is absent from the target-aircraft Full Parameter List.", names(k));
        end
    end
    validation = validation + " + target Full Parameter List";
end

role = repmat("fixed support", size(names));
role(optimized) = "optimized";
parameterTable = table(names, groups, role, values, units, minimum, maximum, ...
    meaning, validation, 'VariableNames', ...
    {'name', 'group', 'role', 'value', 'unit', 'minimum', 'maximum', ...
    'meaning', 'validated_against'});
end

function [names, groups, optimized, minimum, maximum, units, meaning] = bundledSchema()
names = [ ...
    "SCALING_SPEED"; "AIRSPEED_MIN"; "AIRSPEED_CRUISE"; ...
    "RLL_RATE_P"; "RLL_RATE_I"; "RLL_RATE_D"; "RLL_RATE_FF"; "RLL2SRV_TCONST"; ...
    "PTCH_RATE_P"; "PTCH_RATE_I"; "PTCH_RATE_D"; "PTCH_RATE_FF"; "PTCH2SRV_TCONST"; ...
    "KFF_RDDRMIX"; "YAW2SRV_DAMP"; "YAW2SRV_INT"; "YAW2SRV_RLL"; ...
    "YAW2SRV_SLIP"; "YAW2SRV_IMAX"; ...
    "TECS_TIME_CONST"; "TECS_THR_DAMP"; "TECS_INTEG_GAIN"; ...
    "TECS_PTCH_DAMP"; "TECS_SPDWEIGHT"; "TECS_RLL2THR"; ...
    "TECS_CLMB_MAX"; "TECS_SINK_MAX"; "TECS_SINK_MIN"; ...
    "TECS_PITCH_MAX"; "TECS_PITCH_MIN"; "TECS_VERT_ACC"];
groups = [repmat("speed",3,1); repmat("roll",5,1); repmat("pitch",5,1); repmat("yaw",6,1); ...
    repmat("tecs",12,1)];
optimized = [false(3,1); true(5,1); true(5,1); true(5,1); false; true(6,1); false(6,1)];
minimum = [5;5;5; 0.08;0.01;0.001;0;0.4; 0.08;0.01;0.001;0;0.4; ...
    0;0;0;0.8;0;0; 3;0.1;0;0.1;0;5; 0.1;0;0.1;0;-45;1];
maximum = [50;100;100; 0.35;0.6;0.03;3;1; 0.35;0.6;0.03;3;1; ...
    1;2;2;1.2;4;4500; 10;1;0.5;1;2;30; 20;20;10;45;0;10];
units = ["m/s";"m/s";"m/s"; "-";"-";"-";"-";"s"; "-";"-";"-";"-";"s"; ...
    "-";"-";"-";"-";"-";"cdeg"; ...
    "s";"-";"-";"-";"-";"-"; "m/s";"m/s";"m/s";"deg";"deg";"m/s^2"];
meaning = [ ...
    "Fixed-wing airspeed scaling reference"; "Minimum configured airspeed"; "Nominal cruise airspeed"; ...
    "Roll rate P"; "Roll rate I"; "Roll rate D"; "Roll rate feed-forward"; "Roll angle-to-rate time constant"; ...
    "Pitch rate P"; "Pitch rate I"; "Pitch rate D"; "Pitch rate feed-forward"; "Pitch angle-to-rate time constant"; ...
    "Aileron-to-rudder mix"; "Yaw-rate damping"; "Sideslip integrator"; "Coordinated-turn gain"; ...
    "Lateral-acceleration feedback"; "Yaw integrator limit"; ...
    "TECS response time"; "TECS throttle damping"; "TECS integrator gain"; ...
    "TECS pitch damping"; "TECS speed/height weighting"; "Bank-to-throttle compensation"; ...
    "Maximum climb rate"; "Maximum descent rate"; "Minimum sink rate"; ...
    "Automatic-flight pitch maximum"; "Automatic-flight pitch minimum"; "Vertical acceleration limit"];
end
