function outputFile = write_ardupilot_sitl_defaults(P,outputFile)
%WRITE_ARDUPILOT_SITL_DEFAULTS Commit-pinned Plane 4.7.0 defaults.
arguments
    P struct
    outputFile (1,1) string
end
folder = fileparts(outputFile);
if ~isfolder(folder), mkdir(folder); end
parameterTable = mission_planner_parameter_table(P);
rc = P.interface.command_mapping.rc;
map = P.interface.command_mapping;
flightMode = 5; % FBWA
fixed = { ...
    "SERVO1_FUNCTION",4; "SERVO2_FUNCTION",19; "SERVO3_FUNCTION",70; ...
    "SERVO4_FUNCTION",21; "SERVO5_FUNCTION",4; ...
    "SERVO1_MIN",P.actuator.pwm_min(2); ...
    "SERVO1_TRIM",P.actuator.pwm_trim(2); ...
    "SERVO1_MAX",P.actuator.pwm_max(2); ...
    "SERVO1_REVERSED",P.actuator.servo_reversed(2); ...
    "SERVO2_MIN",P.actuator.pwm_min(4); ...
    "SERVO2_TRIM",P.actuator.pwm_trim(4); ...
    "SERVO2_MAX",P.actuator.pwm_max(4); ...
    "SERVO2_REVERSED",P.actuator.servo_reversed(4); ...
    "SERVO3_MIN",P.actuator.pwm_min(1); ...
    "SERVO3_TRIM",P.actuator.pwm_trim(1); ...
    "SERVO3_MAX",P.actuator.pwm_max(1); ...
    "SERVO3_REVERSED",P.actuator.servo_reversed(1); ...
    "SERVO4_MIN",P.actuator.pwm_min(5); ...
    "SERVO4_TRIM",P.actuator.pwm_trim(5); ...
    "SERVO4_MAX",P.actuator.pwm_max(5); ...
    "SERVO4_REVERSED",P.actuator.servo_reversed(5); ...
    "SERVO5_MIN",P.actuator.pwm_min(3); ...
    "SERVO5_TRIM",P.actuator.pwm_trim(3); ...
    "SERVO5_MAX",P.actuator.pwm_max(3); ...
    "SERVO5_REVERSED",P.actuator.servo_reversed(3); ...
    "FLTMODE1",flightMode; "FLTMODE_CH",8; ...
    "SERIAL0_PROTOCOL",2; "SERIAL0_BAUD",115; ...
    "ARMING_REQUIRE",0; "RC7_OPTION",153; ...
    "ROLL_LIMIT_DEG",map.roll_limit_deg; ...
    "PTCH_LIM_MAX_DEG",map.pitch_limit_max_deg; ...
    "PTCH_LIM_MIN_DEG",map.pitch_limit_min_deg; ...
    "STAB_PITCH_DOWN",map.stab_pitch_down_deg; ...
    "TRIM_THROTTLE",map.throttle_cruise_percent; ...
    "LOG_DISARMED",1; "LOG_FILE_DSRMROT",1};
for channel = 1:8
    fixed = [fixed; ... %#ok<AGROW>
        {"RC"+channel+"_MIN",rc.min_us; ...
         "RC"+channel+"_TRIM",rc.trim_us; ...
         "RC"+channel+"_MAX",rc.max_us; ...
         "RC"+channel+"_DZ",rc.deadzone_us}];
end
names = [string(parameterTable.name);string(fixed(:,1))];
values = [double(parameterTable.value);cell2mat(fixed(:,2))];
[~,lastIndex] = unique(flip(names),"stable");
keep = sort(numel(names)-lastIndex+1);
names = names(keep); values = values(keep);
for forbidden = ["LIM_ROLL_CD","LIM_PITCH_MAX","LIM_PITCH_MIN","MODE_CH"]
    if any(names == forbidden)
        error("UAVV541:ObsoleteParameterName", ...
            "Obsolete Plane parameter name is forbidden: %s",forbidden);
    end
end
fid = fopen(outputFile,"w");
if fid < 0, error("UAVV541:SITLDefaultsOpenFailed","Cannot create %s",outputFile); end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
for index = 1:numel(names)
    fprintf(fid,"%s,%.12g\n",names(index),values(index));
end
end
