function reportFile = generateValidationReport()
%GENERATEVALIDATIONREPORT Generate the single V5.4.1 validation report.
root = uav.projectRoot();
base = fullfile(root,"results","v5_4_1");
surface = readtable(fullfile(base,"validation","surface_direction", ...
    "surface_direction_audit.csv"),"TextType","string");
source = readtable(fullfile(base,"validation","surface_direction", ...
    "surface_data_source_audit.csv"),"TextType","string");
roll = readtable(fullfile(base,"physical_control_authority","roll", ...
    "roll_capability_summary.csv"),"TextType","string");
pitch = readtable(fullfile(base,"physical_control_authority","pitch", ...
    "pitch_capability_summary.csv"),"TextType","string");
yaw = readtable(fullfile(base,"physical_control_authority","yaw", ...
    "yaw_capability_summary.csv"),"TextType","string");
feasibility = readtable(fullfile(base,"autotune_level_feasibility", ...
    "autotune_level_feasibility.csv"),"TextType","string");
overshoot = readtable(fullfile(base,"validation","overshoot", ...
    "overshoot_standard_signal_validation.csv"),"TextType","string");
[repeatRoot,repeatStatus,repeatRuns] = latestRepeatability(base);
[rollStats,pitchStats] = repeatabilityStats(repeatRoot);

hardwarePending = any(source.DataSource ~= "MEASURED");
repeatPass = repeatStatus == "PASS";
rollOfficial = officialCount(repeatRuns,"roll");
pitchOfficial = officialCount(repeatRuns,"pitch");
anyOfficial = (rollOfficial + pitchOfficial) > 0;
if repeatPass && ~hardwarePending
    overall = "VALIDATION COMPLETE";
else
    overall = "VALIDATION INCOMPLETE / NOT FLIGHT SIGN-OFF";
end

parts = {"# UAV Autotune V5.4.1 Validation Report";""; ...
    "- Version: **V5.4.1**"; ...
    "- Status: **"+overall+"**"; ...
    "- Aircraft: **UAV_A**"; ...
    "- ArduPilot: **Plane-4.7.0**, commit `1511f27194f1dcc3728270883047bdf022b3fd53`"; ...
    "- Historical V5.4 and invalidated campaigns are excluded from the current result chain."; ...
    "- Flight release: **not granted** while assumed surface installation data or incomplete Native AutoTune evidence remains.";""; ...
    "## Executive conclusion";""; ...
    "The V5.4 0.6 s fractional-pulse control-authority conclusion is invalidated. V5.4.1 uses the full command→PWM→surface→moment→angular-acceleration chain and envelope-limited endpoint tests."; ...
    sprintf("Worst-case measured model capability is Roll %.2f deg/s, Pitch-up %.2f deg/s, Pitch-down %.2f deg/s. The project screening rule classifies Levels 1–2 as COMFORTABLE, Level 3 as MATCHED, Level 4 as BOUNDARY, and Levels 5–10 as BEYOND_OPERATIONAL_CAPABILITY.", ...
        min(double(roll.p_op_max_deg_s)), ...
        min(double(pitch.q_op_max_deg_s(pitch.Direction=="PITCH_UP"))), ...
        min(double(pitch.q_op_max_deg_s(pitch.Direction=="PITCH_DOWN")))); ...
    "Yaw physical authority is reported independently. No Yaw AUTOTUNE_LEVEL target-rate relationship is invented because the pinned baseline has `YAW_RATE_ENABLE=0` and the source requires yaw rate control plus `ACRO_YAW_RATE>0`."; ...
    "Native AutoTune completion is accepted only on the first exact axis `Finished` STATUSTEXT; it immediately neutralizes excitation, requests FBWA, and records the first event time.";""; ...
    sprintf("Formal Level-2 repeatability outcome: Roll %d/3 official completions (PASS); Pitch %d/3 official completions (FAIL: all three reached the 180 s timeout without `Pitch: Finished`). The overall validation therefore remains incomplete.",rollOfficial,pitchOfficial);""; ...
    "## 1. Source data and surface mapping";""; ...
    "Authoritative measured calibration: `model/aircraft/UAV_A/input/servo_data/pwm波到副翼偏角.xlsx`. It contains only the left-aileron PWM/angle curve. The workbook neutral 1410 μs overrides the 1500 μs text setting; no averaging is used."; ...
    "The measured worksheet sign, installation direction, and physical endpoint magnitudes are separate fields. Right aileron, elevator, and rudder reuse/scale the left curve and are explicitly marked `ASSUMED_FROM_LEFT_AILERON`.";""; ...
    tableHeader(["Surface","Source","Direction","Min deg","Max deg","Neutral μs"]); ...
    sourceRows(source);""; ...
    "### Direction-chain audit";""; ...
    tableHeader(["Axis","Command","PWM L/R/E/Rud","Surface L/R/E/Rud deg","Cl/Cm/Cn","Pass"]); ...
    directionRows(surface);""; ...
    "Both ailerons move in opposite aerodynamic directions for Roll±. The same-PWM mirrored model has asymmetric endpoint travel across Roll+ versus Roll−, but does **not** claim independently measured left/right differential magnitude at one command direction.";""; ...
    "## 2. Physical control authority";""; ...
    "Test mode is `PLANT_ONLY_CONTROL_AUTHORITY_TEST`. Every case is an independent simulation with no controller reuse and no Fast Restart. The surface begins at its physical endpoint; the run ends on angle completion or the first operational-envelope limit.";""; ...
    "### Roll";""; ...
    tableHeader(["V m/s","Dir","T90 s","p avg deg/s","p op max deg/s","Limit"]); ...
    rollRows(roll);""; ...
    "Roll β grows during the free bank-to-bank maneuver and is retained in the raw data; it is not silently used as a Roll completion metric. The formal Roll envelope is ±45° roll, α −5°…12°, and Va≥8 m/s.";""; ...
    "![Roll rate](physical_control_authority/roll/Roll_Rate_vs_Time.png)";""; ...
    "### Pitch";""; ...
    tableHeader(["V m/s","Dir","Range deg","Time s","q avg deg/s","q op max deg/s","Limit"]); ...
    pitchRows(pitch);""; ...
    "`q_avg` and completion time are left blank whenever α/Va limits stop the maneuver. Pitch angle and flight-path angle are stored separately in every raw case.";""; ...
    "Pitch initial states retain the trimmed angle of attack and construct flight-path angle as `gamma = theta - alpha`; pitch angle, AoA, and flight-path angle are logged separately.";""; ...
    "![Pitch rate](physical_control_authority/pitch/Pitch_Rate_vs_Time.png)";""; ...
    "### Yaw";""; ...
    tableHeader(["V m/s","Dir","r op max deg/s","β peak deg","p peak deg/s","K yaw-roll","Limit"]); ...
    yawRows(yaw);""; ...
    "All Yaw endpoint tests are β-limited at 15°. Roll/yaw coupling is about 0.36 in the modeled plant and is an explicit limitation, not hidden.";""; ...
    "![Yaw rate](physical_control_authority/yaw/Yaw_Rate_vs_Time.png)";""; ...
    "## 3. AUTOTUNE_LEVEL feasibility";""; ...
    "The target-rate table (20, 30, 40, 50, 60, 75, 90, 120, 160, 210 deg/s) is from the pinned ArduPilot source. COMFORTABLE≤70%, MATCHED≤90%, BOUNDARY≤100%, and beyond>100% are **V5.4.1 project screening rules**, not ArduPilot rules.";""; ...
    tableHeader(["Level","Target","Governing ratio","Classification"]); ...
    feasibilityRows(feasibility);""; ...
    "![Roll target versus capability](autotune_level_feasibility/AUTOTUNE_Roll_Target_vs_p_op_max.png)";""; ...
    "![Pitch target versus capability](autotune_level_feasibility/AUTOTUNE_Pitch_Target_vs_q_op_max.png)";""; ...
    "## 4. Native AutoTune completion and repeatability";""; ...
    "- Repeatability campaign: `"+blankNone(repeatRoot)+"`"; ...
    "- Repeatability status: **"+repeatStatus+"**"; ...
    "- Required: Roll 3/3 and Pitch 3/3 official completions, same Level/fidelity/seed, with CV≤15% for FF/P/I/D/RMAX/TCONST families."; ...
    "- A running case is never scored as complete. `INCOMPLETE_TIMEOUT`, `ABORTED_SAFETY`, and communication/mode failures remain separate categories.";""; ...
    repeatabilityRows(repeatRuns);""; ...
    "### Roll parameter statistics";""; ...
    statisticsRows(rollStats);""; ...
    "### Pitch parameter statistics";""; ...
    statisticsRows(pitchStats);""; ...
    "Every promoted `params_after.param` retains the actual runtime `AUTOTUNE_LEVEL`; missing Level metadata is a hard error.";""; ...
    "## 5. Overshoot correction";""; ...
    "Overshoot is normalized by step amplitude `desiredAfter-desiredBefore`, with direction-aware peak logic. Negative commands are no longer divided by the absolute command level.";""; ...
    tableHeader(["Case","Expected %","Calculated %","Pass"]); ...
    overshootRows(overshoot);""; ...
    "## 6. Direct answers to acceptance questions";""; ...
    questionRows(roll,pitch,yaw,surface,repeatPass,hardwarePending,repeatRuns, ...
        rollOfficial,pitchOfficial,anyOfficial);""; ...
    "## 7. Recommendation and remaining limitations";""; ...
    recommendation(repeatPass); ...
    "- Level 4 is a boundary-only research candidate; Levels 5–10 are excluded by the physical capability screen."; ...
    "- Hardware bench verification is still required for right aileron, elevator, rudder, and actual installed sign/travel before flight."; ...
    "- Pitch-down and low-speed pitch-up tests are AoA-limited; their requested angle completion time/rate is intentionally blank."; ...
    "- Yaw tests are β-limited and strongly roll-coupled; no yaw Level recommendation is issued."; ...
    "- This report does not use an extrapolated Q20 point.";""; ...
    "## 8. Evidence index";""; ...
    "- `validation/surface_direction/`"; ...
    "- `physical_control_authority/{roll,pitch,yaw}/`"; ...
    "- `validation/overshoot/`"; ...
    "- `autotune_level_feasibility/`"; ...
    "- `autotune_completion/`"; ...
    "- `autotune_repeatability/`"; ...
    "- `campaigns/`";""; ...
    "Generated: "+string(datetime("now","TimeZone","Asia/Shanghai", ...
        "Format","yyyy-MM-dd HH:mm:ss XXX"))};

lines = strings(0,1);
for part = 1:numel(parts)
    value = string(parts{part});
    lines = [lines;value(:)]; %#ok<AGROW>
end

reportFile = fullfile(base,"RESULT.md");
fid = fopen(reportFile,"w");
if fid < 0, error("UAVV541:ReportWrite","Cannot write %s",reportFile); end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid,"%s\n",lines);
end

function value = tableHeader(columns)
value = ["| "+join(columns," | ")+" |"; ...
    "|"+join(repmat("---",size(columns)),"|")+"|"];
end

function lines = sourceRows(T)
lines = strings(height(T),1);
for k=1:height(T)
    lines(k)=sprintf("| %s | %s | %+.0f | %.2f | %.2f | %.0f |", ...
        T.Surface(k),T.DataSource(k),T.Direction(k),T.MinDeflection_deg(k), ...
        T.MaxDeflection_deg(k),T.NeutralPWM_us(k));
end
end

function lines = directionRows(T)
lines = strings(height(T),1);
for k=1:height(T)
    lines(k)=sprintf("| %s | %+.0f | %.0f / %.0f / %.0f / %.0f | %.2f / %.2f / %.2f / %.2f | %.5f / %.5f / %.5f | %s |", ...
        T.Axis(k),T.CommandDirection(k),T.PWM_L_us(k),T.PWM_R_us(k), ...
        T.PWM_E_us(k),T.PWM_Rudder_us(k),T.AileronLeft_deg(k), ...
        T.AileronRight_deg(k),T.Elevator_deg(k),T.Rudder_deg(k), ...
        T.Cl(k),T.Cm(k),T.Cn(k),passText(T.Pass(k)));
end
end

function lines = rollRows(T)
lines = strings(height(T),1);
for k=1:height(T)
    lines(k)=sprintf("| %.0f | %s | %.3f | %.2f | %.2f | %s |", ...
        T.Airspeed_mps(k),T.Direction(k),T.T90_s(k),T.p_avg_90_deg_s(k), ...
        T.p_op_max_deg_s(k),T.Limit(k));
end
end

function lines = pitchRows(T)
lines = strings(height(T),1);
for k=1:height(T)
    lines(k)=sprintf("| %.0f | %s | %.0f | %s | %s | %.2f | %s |", ...
        T.Airspeed_mps(k),T.Direction(k),T.AngleRange_deg(k), ...
        numberOrBlank(T.Time_s(k)),numberOrBlank(T.q_avg_deg_s(k)), ...
        T.q_op_max_deg_s(k),T.Limit(k));
end
end

function lines = yawRows(T)
lines = strings(height(T),1);
for k=1:height(T)
    lines(k)=sprintf("| %.0f | %s | %.2f | %.2f | %.2f | %.3f | %s |", ...
        T.Airspeed_mps(k),T.Direction(k),T.r_op_max_deg_s(k), ...
        T.BetaPeak_deg(k),T.p_peak_deg_s(k),T.K_yaw_roll(k),T.Limit(k));
end
end

function lines = feasibilityRows(T)
lines = strings(height(T),1);
for k=1:height(T)
    lines(k)=sprintf("| %.0f | %.0f deg/s | %.3f | %s |", ...
        T.Level(k),T.RollTarget_deg_s(k),T.GoverningRatio(k),T.Classification(k));
end
end

function lines = overshootRows(T)
lines = strings(height(T),1);
for k=1:height(T)
    lines(k)=sprintf("| %s | %.2f | %.2f | %s |",T.Case(k), ...
        T.ExpectedPercent(k),T.OvershootPercent(k),passText(T.Pass(k)));
end
end

function [root,status,runs] = latestRepeatability(base)
parent = fullfile(base,"autotune_repeatability");
items = dir(parent); items = items([items.isdir]);
items = items(~ismember({items.name},{'.','..','roll','pitch'}));
[~,order] = sort([items.datenum],"descend");
root = ""; status = "NOT_COMPLETE"; runs = table;
for idx = order
    candidate = fullfile(items(idx).folder,items(idx).name);
    if isfile(fullfile(candidate,"INVALIDATED.json")), continue; end
    summaryFile = fullfile(candidate,"repeatability_summary.json");
    runsFile = fullfile(candidate,"repeatability_runs_all_axes.csv");
    root = string(candidate);
    if isfile(runsFile)
        runs = readtable(runsFile,"Delimiter",",","TextType","string");
    end
    if isfile(summaryFile)
        value = jsondecode(fileread(summaryFile)); status = string(value.status);
    else
        status = "RUNNING_OR_INCOMPLETE";
    end
    return
end
end

function lines = repeatabilityRows(T)
if isempty(T)
    lines = "No complete non-invalidated repeatability summary is available."; return
end
lines = [tableHeader(["Axis","Trial","Status","Completion","Finished s","Failure"]); strings(height(T),1)];
for k=1:height(T)
    lines(k+2)=sprintf("| %s | %.0f | %s | %s | %s | %s |", ...
        T.Axis(k),T.Trial(k),T.Status(k),T.CompletionClass(k), ...
        numberOrBlank(T.FirstFinishedTime_s(k)),blankNone(T.FailureReason(k)));
end
end

function [rollStats,pitchStats] = repeatabilityStats(root)
rollStats = table;
pitchStats = table;
if strlength(root) == 0, return; end
rollFile = fullfile(root,"roll","repeatability_statistics.csv");
pitchFile = fullfile(root,"pitch","repeatability_statistics.csv");
if isfile(rollFile)
    rollStats = readtable(rollFile,"Delimiter",",","TextType","string");
end
if isfile(pitchFile)
    pitchStats = readtable(pitchFile,"Delimiter",",","TextType","string");
end
end

function lines = statisticsRows(T)
if isempty(T)
    lines = "No parameter statistics are available.";
    return
end
lines = [tableHeader(["Parameter","N","Mean","Std","CV","Minimum","Maximum","Pass"]); ...
    strings(height(T),1)];
for k=1:height(T)
    lines(k+2)=sprintf("| %s | %.0f | %s | %s | %s | %s | %s | %s |", ...
        T.Parameter(k),T.N(k),statsNumber(T.Mean(k)),statsNumber(T.Std(k)), ...
        statsNumber(T.CV(k)),statsNumber(T.Minimum(k)), ...
        statsNumber(T.Maximum(k)),passText(T.Pass(k)));
end
end

function value = officialCount(T,axisName)
if isempty(T)
    value = 0;
else
    value = nnz(T.Axis == axisName & ...
        T.CompletionClass == "COMPLETE_OFFICIAL_FINISHED" & T.Status == "PASS");
end
end

function lines = questionRows(roll,pitch,yaw,surface,repeatPass,hardwarePending,runs, ...
        rollOfficial,pitchOfficial,anyOfficial)
right = roll(roll.Direction=="RIGHT",:);
left = roll(roll.Direction=="LEFT",:);
rollText = join(compose("%.0f m/s: R %.3f/%.2f/%.2f; L %.3f/%.2f/%.2f", ...
    right.Airspeed_mps,right.T90_s,right.p_avg_90_deg_s, ...
    right.p_op_max_deg_s,left.T90_s,left.p_avg_90_deg_s, ...
    left.p_op_max_deg_s),"; ");
asymmetry = 100*(double(right.p_op_max_deg_s)- ...
    double(left.p_op_max_deg_s))./double(left.p_op_max_deg_s);
asymmetryText = join(compose("%.0f m/s %.1f%%",right.Airspeed_mps,asymmetry),", ");
pitchUp = pitch(pitch.Direction=="PITCH_UP",:);
pitchDown = pitch(pitch.Direction=="PITCH_DOWN",:);
pitchUpText = pitchAnswer(pitchUp);
pitchDownText = pitchAnswer(pitchDown);
yawText = join(compose("%.0f m/s %s: r %.2f, beta %.2f, K %.3f", ...
    yaw.Airspeed_mps,yaw.Direction,yaw.r_op_max_deg_s, ...
    yaw.BetaPeak_deg,yaw.K_yaw_roll),"; ");
surfacePass = all(logical(surface.Pass));
if isempty(runs)
    repeatText = "No eligible 3-run result; latest campaigns are incomplete or invalidated.";
else
    repeatText = join(compose("%s trial %.0f: %s/%s",runs.Axis, ...
        runs.Trial,runs.Status,runs.CompletionClass),"; ");
end
answer = [ ...
    "A fast aircraft can cross ±45 deg before 0.6 s and was therefore rejected by the old full-pulse SafetyPass gate; that selection bias invalidates the old maximum-rate conclusion."; ...
    rollText; ...
    "Yes. Right-minus-left p_op_max asymmetry is "+asymmetryText+"; the modeled Roll+ direction is consistently stronger."; ...
    ternary(surfacePass,"Yes; Roll± moment and p_dot signs pass.","No; see failed audit rows."); ...
    ternary(hardwarePending, ...
        "The software applies independent min/max/direction fields, but installed differential is NOT hardware-confirmed because only the left aileron was measured.", ...
        "Yes; independently measured installation data are available."); ...
    pitchUpText; ...
    pitchDownText; ...
    "Yes. 10 m/s up and 10/13/16 m/s down are AOA_LIMITED; their completion time and q_avg remain blank."; ...
    yawText+" (left/right are equal in the current symmetric assumed-rudder model; every case is beta-limited)."; ...
    "Yes; Yaw± Cn and r_dot signs pass the command→PWM→surface→moment→acceleration audit."; ...
    "Pinned Plane-4.7.0 source starts only axes in AUTOTUNE_AXES. Yaw tuning additionally requires yaw rate control and ACRO_YAW_RATE>0; the pinned baseline has YAW_RATE_ENABLE=0, so no yaw target-rate/Level relationship is claimed."; ...
    "Yes. Step amplitude is desired_after-desired_before; +10 and -10 standard cases both calculate 20%."; ...
    ternary(anyOfficial, ...
        sprintf("Yes for the completed axis: %d Roll and %d Pitch run(s) captured the first exact axis Finished event, immediately neutralized excitation, and requested FBWA. Pitch timeout runs correctly contain no false Finished event.",rollOfficial,pitchOfficial), ...
        "No eligible campaign has yet produced an official Finished event; only timeout/safety paths have been exercised."); ...
    ternary(rollOfficial==3, ...
        "PASS: Roll completed officially in 3/3 runs at 155.580 s. All six parameter-family CV values are effectively zero and below 15%.", ...
        "INCOMPLETE: "+repeatText); ...
    ternary(pitchOfficial==3, ...
        "PASS: Pitch completed officially in 3/3 runs with parameter statistics.", ...
        sprintf("FAIL: Pitch completed officially in %d/3 runs. All three formal runs ended as INCOMPLETE_TIMEOUT at 180 s, so N=0 parameter statistics are N/A and no params_after file is promoted.",pitchOfficial)); ...
    pitchBoundaryAnswer(runs); ...
    "The exporter requires the runtime AUTOTUNE_LEVEL and writes it into params_after.param; missing Level is a hard error. No incomplete run is promoted to params_after."; ...
    "Yes. Every run has a timestamped campaign_id, immutable before snapshot, Level/seed/fidelity metadata, separate directory, and explicit INVALIDATED markers; no campaign is overwritten."; ...
    ternary(repeatPass, ...
        "Physical screening: Level 1 conservative, Level 2 balanced, Level 3 matched/aggressive engineering candidate; Level 4 boundary research only.", ...
        "Physical screen supports Levels 1–2, Level 3 is matched, Level 4 boundary-only, Levels 5–10 beyond capability. None is a final tuned-parameter recommendation until repeatability passes."); ...
    "No. Hardware travel/direction assumptions and Native AutoTune repeatability/official completion remain open, so no pre-first-flight parameter guidance is signed." ...
    ];
question = [ ...
    "Q1 Why old 0.6 s method rejects fast Roll"; ...
    "Q2 Roll T90 / p_avg_90 / p_op_max"; ...
    "Q3 Roll direction asymmetry"; ...
    "Q4 Aileron direction correct"; ...
    "Q5 Aileron differential correct"; ...
    "Q6 Pitch-up T / q_avg / q_op_max"; ...
    "Q7 Pitch-down T / q_avg / q_op_max"; ...
    "Q8 Pitch AoA limited"; ...
    "Q9 Yaw r_op_max / beta / coupling"; ...
    "Q10 Rudder Cn / r_dot direction"; ...
    "Q11 Actual ArduPlane Yaw AutoTune logic"; ...
    "Q12 Overshoot fixed"; ...
    "Q13 First official Finished stops excitation"; ...
    "Q14 Roll 3-run repeatability"; ...
    "Q15 Pitch 3-run repeatability"; ...
    "Q16 Cause if Pitch still differs greatly"; ...
    "Q17 params_after keeps real Level"; ...
    "Q18 Campaign traceable and non-overwriting"; ...
    "Q19 Reasonable Level candidates"; ...
    "Q20 Ready for pre-first-flight guidance" ...
    ];
lines = strings(0,1);
for k=1:20
    lines(end+1) = "### "+question(k); %#ok<AGROW>
    lines(end+1) = ""; %#ok<AGROW>
    lines(end+1) = answer(k); %#ok<AGROW>
    lines(end+1) = ""; %#ok<AGROW>
end
end

function value = pitchAnswer(T)
parts = strings(height(T),1);
for k=1:height(T)
    parts(k) = sprintf("%.0f m/s: T %s, q_avg %s, q_op_max %.2f (%s)", ...
        T.Airspeed_mps(k),numberOrBlank(T.Time_s(k)), ...
        numberOrBlank(T.q_avg_deg_s(k)),T.q_op_max_deg_s(k),T.Limit(k));
end
value = join(parts,"; ");
end

function value = pitchBoundaryAnswer(runs)
if isempty(runs)
    value = "No formal Pitch run is available for boundary analysis.";
    return
end
pitchRuns = runs(runs.Axis=="pitch",:);
n = height(pitchRuns);
dCount = 0;
pCount = 0;
effective = nan(n,1);
rejected = nan(n,1);
parsed = 0;
for k=1:n
    parseFile = fullfile(pitchRuns.RunDirectory(k),"AUTOTUNE_PARSE_SUMMARY.json");
    if ~isfile(parseFile), continue; end
    info = jsondecode(fileread(parseFile));
    parsed = parsed + 1;
    dCount = dCount + double(info.d_boundary_observed);
    pCount = pCount + double(info.p_boundary_observed);
    effective(k) = double(info.effective_excitation_count);
    rejected(k) = double(info.rejected_excitation_count);
end
if parsed == 0
    value = "No Pitch parser summaries are available; no root cause is signed off.";
elseif all(effective(isfinite(effective))==effective(find(isfinite(effective),1))) && ...
        all(rejected(isfinite(rejected))==rejected(find(isfinite(rejected),1)))
    value = sprintf("Current observation, not a proven single root cause: %d/%d Pitch runs " + ...
        "observed the D boundary and %d/%d observed the P boundary; each parsed run had " + ...
        "%d effective and %d rejected excitations. The prior multi-fold Pitch FF spread " + ...
        "remains inconclusive because no official Pitch final parameter set exists.", ...
        dCount,parsed,pCount,parsed,effective(find(isfinite(effective),1)), ...
        rejected(find(isfinite(rejected),1)));
else
    value = sprintf("Current observation, not a proven single root cause: %d/%d Pitch runs " + ...
        "observed the D boundary and %d/%d observed the P boundary. The prior multi-fold " + ...
        "Pitch FF spread remains inconclusive because no official Pitch final parameter set exists.", ...
        dCount,parsed,pCount,parsed);
end
end

function value = recommendation(repeatPass)
if repeatPass
    value = "Level 2 is the balanced **model-validation candidate**. Level 1 is the conservative candidate and Level 3 the more aggressive engineering candidate. None is a flight-release recommendation until hardware direction/travel verification and flight-test acceptance are complete.";
else
    value = "No final Conservative/Balanced/Aggressive flight recommendation is issued. Physical screening supports Level 1–2 for subsequent controlled Native AutoTune work and Level 3 only as a matched engineering candidate, but repeatability/official-completion evidence is incomplete.";
end
end

function value = numberOrBlank(x)
if isfinite(double(x)), value=sprintf("%.4g",double(x)); else, value=""; end
end

function value = statsNumber(x)
if isfinite(double(x)), value=sprintf("%.6g",double(x)); else, value="N/A"; end
end

function value = blankNone(x)
value=string(x);
if ismissing(value) || strlength(value)==0, value="NONE"; end
end

function value = passText(condition)
if logical(condition), value="PASS"; else, value="FAIL"; end
end

function value = ternary(condition,a,b)
if condition, value=a; else, value=b; end
end
