function parameters = sensorParameterOverrides(P)
%SENSORPARAMETEROVERRIDES Map V5.4.1 fidelity to Plane-4.7.0 SIM parameters.

fidelity = lower(string(P.fidelity.sensor));
if fidelity == "ideal"
    parameters = idealParameters();
    return
end
if fidelity ~= "engineering"
    error("UAVV541:SensorFidelity","Unsupported sensor fidelity '%s'.",fidelity);
end

% Plane-4.7.0 SITL.cpp declares SIM_GYR1_BIAS in rad/s.  P.sensor stores
% the same SI unit, so any rad2deg conversion would amplify bias 57.3x.
gBias = P.sensor.gyroscope.bias(:);
aBias = P.sensor.accelerometer.bias(:);
gpsVelocity = P.sensor.gps_velocity.noise_std(:);
magOffset = P.sensor.native_magnetometer_offset_mgauss(:);
parameters = struct( ...
    "SIM_GYR1_RND",rad2deg(max(P.sensor.gyroscope.noise_std)), ...
    "SIM_GYR1_BIAS_X",gBias(1),"SIM_GYR1_BIAS_Y",gBias(2), ...
    "SIM_GYR1_BIAS_Z",gBias(3), ...
    "SIM_ACC1_RND",max(P.sensor.accelerometer.noise_std), ...
    "SIM_ACC1_BIAS_X",aBias(1),"SIM_ACC1_BIAS_Y",aBias(2), ...
    "SIM_ACC1_BIAS_Z",aBias(3), ...
    "SIM_DRIFT_SPEED",rad2deg(max(P.sensor.gyroscope.drift_amplitude)), ...
    "SIM_DRIFT_TIME",1/max(60*P.sensor.gyroscope.drift_frequency_hz,eps), ...
    "SIM_GPS1_LAG_MS",1000*P.sensor.gps_position.delay_s, ...
    "SIM_GPS1_HZ",round(1/P.sensor.gps_position.sample_time_s), ...
    "SIM_GPS1_ACC",max(P.sensor.gps_position.noise_std), ...
    "SIM_GPS1_NOISE",P.sensor.gps_position.noise_std(3), ...
    "SIM_GPS1_VERR_X",gpsVelocity(1), ...
    "SIM_GPS1_VERR_Y",gpsVelocity(2), ...
    "SIM_GPS1_VERR_Z",gpsVelocity(3), ...
    "SIM_BARO_RND",P.sensor.barometer.noise_std, ...
    "SIM_BARO_DRIFT",P.sensor.barometer.drift_amplitude* ...
        2*pi*P.sensor.barometer.drift_frequency_hz, ...
    "SIM_BARO_DELAY",1000*P.sensor.barometer.delay_s, ...
    "SIM_MAG_RND",max(abs(magOffset)), ...
    "SIM_MAG_DELAY",1000*P.sensor.magnetometer.delay_s, ...
    "SIM_MAG1_OFS_X",magOffset(1),"SIM_MAG1_OFS_Y",magOffset(2), ...
    "SIM_MAG1_OFS_Z",magOffset(3), ...
    "SIM_ARSPD_RND",P.sensor.airspeed.noise_std, ...
    "SIM_ARSPD_OFS",P.sensor.airspeed.bias);
end

function parameters = idealParameters()
names = ["SIM_GYR1_RND","SIM_GYR1_BIAS_X","SIM_GYR1_BIAS_Y", ...
    "SIM_GYR1_BIAS_Z","SIM_ACC1_RND","SIM_ACC1_BIAS_X", ...
    "SIM_ACC1_BIAS_Y","SIM_ACC1_BIAS_Z","SIM_DRIFT_SPEED", ...
    "SIM_DRIFT_TIME","SIM_GPS1_LAG_MS","SIM_GPS1_ACC", ...
    "SIM_GPS1_NOISE","SIM_GPS1_VERR_X", ...
    "SIM_GPS1_VERR_Y","SIM_GPS1_VERR_Z","SIM_BARO_RND", ...
    "SIM_BARO_DRIFT","SIM_BARO_DELAY","SIM_MAG_RND", ...
    "SIM_MAG_DELAY","SIM_MAG1_OFS_X","SIM_MAG1_OFS_Y", ...
    "SIM_MAG1_OFS_Z","SIM_ARSPD_RND","SIM_ARSPD_OFS"];
parameters = struct;
for name = names
    parameters.(name) = 0;
end
parameters.SIM_GPS1_HZ = 5;
end
