function evidence = startModeSession(modeName,runDirectory,cfg,options)
%STARTMODESESSION Start nonblocking ACK/read-back control alongside simulation.
arguments
    modeName (1,1) string {mustBeMember(modeName,["FBWA","AUTOTUNE"])}
    runDirectory (1,1) string
    cfg struct
    options.Distro (1,1) string = "Ubuntu-24.04"
end
stopTime = double(cfg.scenario.stop_time_s);
exitMargin = min(3,max(1,0.2*stopTime));
defaultExit = max(0.5,stopTime-exitMargin);
scoringStart = fieldOr(cfg.scenario,"scoring_start_time_s", ...
    double(cfg.project.mode_gate.minimum_startup_guard_s)+4.0);
scoringEnd = fieldOr(cfg.scenario,"scoring_end_time_s",defaultExit);
exitAfter = max(defaultExit,scoringEnd);
gate = cfg.project.mode_gate;
autotuneAxis = "";
if modeName == "AUTOTUNE", autotuneAxis = lower(string(cfg.scenario.axis)); end
script = fullfile(uav.projectRoot(),"scripts","sitl", ...
    "start_mode_session_wsl.ps1");
try
    detail = uav.invokePowerShell(script,["-EntryMode",modeName, ...
        "-RunDirectory",runDirectory,"-ExitAfterSimSeconds",string(exitAfter), ...
        "-ScoringStartSimSeconds",string(scoringStart), ...
        "-ScoringEndSimSeconds",string(scoringEnd), ...
        "-MinimumStartupGuardSeconds",string(gate.minimum_startup_guard_s), ...
        "-StartupTimeoutWallSeconds",string(gate.startup_timeout_wall_s), ...
        "-HeartbeatRequiredCount",string(gate.heartbeat_required_count), ...
        "-FdmRequiredCount",string(gate.fdm_required_count), ...
        "-AttitudeAlignmentRequiredCount", ...
            string(gate.attitude_alignment_required_count), ...
        "-AttitudeAlignmentRollPitchToleranceDeg", ...
            string(gate.attitude_alignment_roll_pitch_tolerance_deg), ...
        "-AttitudeAlignmentYawToleranceDeg", ...
            string(gate.attitude_alignment_yaw_tolerance_deg), ...
        "-ModeRequiredCount",string(gate.mode_required_count), ...
        "-ModeStableSimSeconds",string(gate.mode_stable_sim_s), ...
        "-ModeHeartbeatTimeoutWallSeconds", ...
            string(gate.mode_heartbeat_timeout_wall_s), ...
        "-ParameterQueryName",string(gate.parameter_query_name), ...
        "-AutotuneAxis",autotuneAxis, ...
        "-Distro",options.Distro]);
    evidence = struct("pass",true,"state","STARTED", ...
        "entry_mode",modeName,"exit_after_sim_seconds",exitAfter, ...
        "scoring_start_sim_seconds",scoringStart, ...
        "scoring_end_sim_seconds",scoringEnd, ...
        "autotune_axis",autotuneAxis, ...
        "detail",string(detail));
catch ME
    evidence = struct("pass",false,"state","START_FAILED", ...
        "entry_mode",modeName,"failure_reason","MODE_CHANGE_FAIL", ...
        "detail",string(ME.message));
end
writeJson(fullfile(runDirectory,"mode_session_launch.json"),evidence);
end

function value = fieldOr(s,name,default)
if isfield(s,name), value = double(s.(name)); else, value = default; end
end

function writeJson(filePath,value)
fid = fopen(filePath,"w");
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid,"%s",jsonencode(value,"PrettyPrint",true));
end
